{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TableObjectError"}],"platforms":["macOS"],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations"],"title":"Default Implementations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/postgresclientorm\/tableobjecterror"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"},"relationshipsSections":[{"identifiers":["doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP","doc:\/\/PostgresClientORM\/s5ErrorP","doc:\/\/PostgresClientORM\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM"]]},"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TableObjectError","kind":"identifier"}],"title":"TableObjectError","roleHeading":"Enumeration","symbolKind":"enum","externalID":"s:17PostgresClientORM16TableObjectErrorO","modules":[{"name":"PostgresClientORM"}]},"references":{"doc://PostgresClientORM/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/PostgresClientORM\/s5ErrorP"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError":{"navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/postgresclientorm\/tableobjecterror","abstract":[],"title":"TableObjectError","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TableObjectError","kind":"identifier"}]},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/errorDescription":{"kind":"symbol","title":"errorDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/postgresclientorm\/tableobjecterror\/errordescription","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/Error-Implementations":{"role":"collectionGroup","kind":"article","title":"Error Implementations","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/error-implementations","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations","type":"topic"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/general(_:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"general","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)","url":"\/documentation\/postgresclientorm\/tableobjecterror\/general(_:)","title":"TableObjectError.general(_:)","kind":"symbol","abstract":[]},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/unsupported":{"url":"\/documentation\/postgresclientorm\/tableobjecterror\/unsupported","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsupported"}],"abstract":[],"identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported","kind":"symbol","title":"TableObjectError.unsupported","role":"symbol"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/LocalizedError-Implementations":{"url":"\/documentation\/postgresclientorm\/tableobjecterror\/localizederror-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations","kind":"article","title":"LocalizedError Implementations","role":"collectionGroup"},"doc://PostgresClientORM/documentation/PostgresClientORM":{"type":"topic","title":"PostgresClientORM","kind":"symbol","role":"collection","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","url":"\/documentation\/postgresclientorm","abstract":[]},"doc://PostgresClientORM/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/s8SendableP"},"doc://PostgresClientORM/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP"}}}