{"metadata":{"modules":[{"name":"PostgresClientORM"}],"role":"symbol","title":"TableObjectError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TableObjectError","kind":"identifier"}],"externalID":"s:17PostgresClientORM16TableObjectErrorO","roleHeading":"Enumeration","navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"symbolKind":"enum"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP","doc:\/\/PostgresClientORM\/s5ErrorP","doc:\/\/PostgresClientORM\/s8SendableP"]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported"]},{"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"],"title":"Instance Properties"},{"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/postgresclientorm\/tableobjecterror"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TableObjectError"}],"platforms":["macOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM"]]},"references":{"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/Error-Implementations":{"url":"\/documentation\/postgresclientorm\/tableobjecterror\/error-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations","abstract":[],"title":"Error Implementations"},"doc://PostgresClientORM/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/s5ErrorP","title":"Swift.Error"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError":{"title":"TableObjectError","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError","url":"\/documentation\/postgresclientorm\/tableobjecterror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TableObjectError"}],"navigatorTitle":[{"kind":"identifier","text":"TableObjectError"}],"type":"topic"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/unsupported":{"kind":"symbol","title":"TableObjectError.unsupported","type":"topic","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported","url":"\/documentation\/postgresclientorm\/tableobjecterror\/unsupported","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://PostgresClientORM/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/LocalizedError-Implementations":{"title":"LocalizedError Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations","url":"\/documentation\/postgresclientorm\/tableobjecterror\/localizederror-implementations","kind":"article","abstract":[]},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription","type":"topic","title":"errorDescription","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/errordescription"},"doc://PostgresClientORM/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/s8SendableP","title":"Swift.Sendable"},"doc://PostgresClientORM/documentation/PostgresClientORM":{"type":"topic","kind":"symbol","title":"PostgresClientORM","url":"\/documentation\/postgresclientorm","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","role":"collection","abstract":[]},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/general(_:)":{"abstract":[],"type":"topic","title":"TableObjectError.general(_:)","url":"\/documentation\/postgresclientorm\/tableobjecterror\/general(_:)","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"general","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol"}}}