{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TableObjectError","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported"]},{"title":"Instance Properties","identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"]},{"identifiers":["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/postgresclientorm\/tableobjecterror"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM"]]},"metadata":{"symbolKind":"enum","externalID":"s:17PostgresClientORM16TableObjectErrorO","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"TableObjectError"}],"title":"TableObjectError","modules":[{"name":"PostgresClientORM"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TableObjectError"}],"role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP","doc:\/\/PostgresClientORM\/s5ErrorP","doc:\/\/PostgresClientORM\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"references":{"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/error-implementations","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/Error-Implementations"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/LocalizedError-Implementations":{"role":"collectionGroup","kind":"article","title":"LocalizedError Implementations","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/localizederror-implementations","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/LocalizedError-Implementations"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TableObjectError"}],"role":"symbol","kind":"symbol","title":"TableObjectError","type":"topic","navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"},"doc://PostgresClientORM/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/PostgresClientORM\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/unsupported":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unsupported","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"TableObjectError.unsupported","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/unsupported","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/unsupported"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","title":"errorDescription","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/errordescription","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"},"doc://PostgresClientORM/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/s5ErrorP"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/general(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"TableObjectError.general(_:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/general(_:)","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/general(_:)"},"doc://PostgresClientORM/documentation/PostgresClientORM":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","title":"PostgresClientORM","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","url":"\/documentation\/postgresclientorm"},"doc://PostgresClientORM/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/PostgresClientORM\/s8SendableP","title":"Swift.Sendable"}}}