{"hierarchy":{"paths":[["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/postgresclientorm\/tableobjecterror\/errordescription"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"PostgresClientORM"}],"role":"symbol","externalID":"s:17PostgresClientORM16TableObjectErrorO16errorDescriptionSSSgvp","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription"},"identifier":{"url":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription","interfaceLanguage":"swift"},"references":{"doc://PostgresClientORM/documentation/PostgresClientORM":{"abstract":[],"kind":"symbol","url":"\/documentation\/postgresclientorm","type":"topic","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","title":"PostgresClientORM","role":"collection"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError":{"type":"topic","title":"TableObjectError","url":"\/documentation\/postgresclientorm\/tableobjecterror","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TableObjectError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError","navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"role":"symbol"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/errorDescription":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/postgresclientorm\/tableobjecterror\/errordescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","title":"errorDescription","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"}}}