{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"sections":[],"metadata":{"role":"symbol","title":"errorDescription","externalID":"s:17PostgresClientORM16TableObjectErrorO16errorDescriptionSSSgvp","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"PostgresClientORM"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/postgresclientorm\/tableobjecterror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TableObjectError"}],"role":"symbol","kind":"symbol","title":"TableObjectError","type":"topic","navigatorTitle":[{"text":"TableObjectError","kind":"identifier"}],"abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError"},"doc://PostgresClientORM/documentation/PostgresClientORM/TableObjectError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","title":"errorDescription","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/postgresclientorm\/tableobjecterror\/errordescription","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM\/TableObjectError\/errorDescription"},"doc://PostgresClientORM/documentation/PostgresClientORM":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","title":"PostgresClientORM","identifier":"doc:\/\/PostgresClientORM\/documentation\/PostgresClientORM","url":"\/documentation\/postgresclientorm"}}}